bot_runtime:
  message_batch_delay_sec: 5
  heartbeat_timeout_sec: 30
  report_delay_sec: 5
  bot_ids:
    - 1
    - 2
    - 4
  total_balance_offset: 0.0
  total_profit_offset: 0.0

http_server:
  port: 8080